/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.FileNotFoundException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    @DisplayName("Should return a quote and author name.")
    public void appReturnsQuoteAndAuthor() throws FileNotFoundException {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getRandomQuoteAndAuthor(), "App should return a quote and author.");
    }
}
